### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by rainmanh** [AppliedTrust/traildash#21]
Hi

I am getting that error on the subject probably because I was trying to import OLD data within the same stream as the new (basically trying to re-use the same SQS queue)
This is the stack trace:

```
panic: runtime error: index out of range

goroutine 6 [running]:
main.(*config).workLogs(0xc208066200)
    /data/go/src/github.com/appliedtrust/traildash/traildash.go:257 +0x10ac
created by main.main
    /data/go/src/github.com/appliedtrust/traildash/traildash.go:133 +0x269

goroutine 1 [chan receive]:
main.main()
    /data/go/src/github.com/appliedtrust/traildash/traildash.go:141 +0x5b3

goroutine 5 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [IO wait]:
net.(*pollDesc).Wait(0xc2080104c0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080104c0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010460, 0x0, 0x7fcab46a9c70, 0xc20800b928)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038058, 0x57a624, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208038058, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080407e0, 0x7fcab46ab268, 0xc208038058, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080407e0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x7f5950, 0xc, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1808 +0xba
main.(*config).serveKibana(0xc208066200)
    /data/go/src/github.com/appliedtrust/traildash/traildash.go:155 +0xfd
created by main.main
    /data/go/src/github.com/appliedtrust/traildash/traildash.go:134 +0x283

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc20807c210)
    /usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc20807c210)
    /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:661 +0xcbc
```

I am looking around but I do not know where the data is being stored in apart of in the elastic search engine?
As I am testing I am ok to clear anything up, but at the present I have not found where about (apart of dropping the data from elastic search and starting again, but still it does not fix the issue)

Thanks!!

**Comment by nmcclain** [comment]
@rainmanh and/or @Heuriskein - we need a sample of one of the messages that causes this error.  We just published a new release that should log the SQS ID of the message that generates the error.  Please go to the AWS console, grab the JSON contents of that message, and paste them here so we can get to the bottom of this.  Thanks!

**Comment by nmcclain** [comment]
@rainmanh and/or @Heuriskein - I would love to tackle this but need your help with a sample message.  Thanks!!

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
