### ISSUE TITLE
Backfill.py Script Error

### ISSUE THREAD

**Issue by mandeepbal** [AppliedTrust/traildash#25]
Hi, I've exported the correct env variables before running the backfill.py script. However I'm getting this error during the for loop.

```
Traceback (most recent call last):
  File "backfill.py", line 20, in <module>
    for item in bucket.objects.all():
  File "/Library/Python/2.7/site-packages/boto3/resources/collection.py", line 82, in __iter__
    for page in self.pages():
  File "/Library/Python/2.7/site-packages/boto3/resources/collection.py", line 141, in pages
    merge_dicts(params, cleaned_params, append_lists=True)
TypeError: merge_dicts() got an unexpected keyword argument 'append_lists'
```

**Comment by mandeepbal** [comment]
i ran the script in the shell and i get the same result..

```
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from os import environ
>>> 
>>> import boto3
>>> 
>>> 
>>> if not all([environ.get('AWS_S3_BUCKET'), environ.get('AWS_SQS_URL')]):
...     print('You have to specify the AWS_S3_BUCKET and AWS_SQS_URL environment variables.')
...     print('Check the "Backfilling data" section of the README file for more info.')
...     exit(1)
... 
>>> bucket = boto3.resource('s3').Bucket(environ.get('AWS_S3_BUCKET'))
>>> queue = boto3.resource('sqs').Queue(environ.get('AWS_SQS_URL'))
>>> 
>>> items_queued = 0
>>> for item in bucket.objects.all():
...     if not item.key.endswith('.json.gz'):
...          continue
...     queue.send_message(
... 
...         MessageBody=json.dumps({
...             'Message': json.dumps({
...                 's3Bucket': environ.get('AWS_S3_BUCKET'),
...                 's3ObjectKey': [item.key]
...             })
...         })
...     )
...     items_queued += 1
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/boto3/resources/collection.py", line 82, in __iter__
    for page in self.pages():
  File "/Library/Python/2.7/site-packages/boto3/resources/collection.py", line 141, in pages
    merge_dicts(params, cleaned_params, append_lists=True)
TypeError: merge_dicts() got an unexpected keyword argument 'append_lists'
```

**Comment by mandeepbal** [comment]
fixed the issue by using latest version of python3
